Plotly.d3.json(
  "https://dsci550-sp21-hw3-part2.s3-us-west-2.amazonaws.com/hw3_part2_viz4_data_with_coords_split.json",
  function (err, rows) {
    var data_0 = [
      {
        x: rows.x0,
        y: rows.y0,
        z: rows.z0,
        mode: "markers",
        type: "scatter3d",
        marker: {
          color: "red",
          size: 5,
        },
      },
      {
        alphahull: 7,
        opacity: 0.1,
        type: "mesh3d",
        x: rows.x0,
        y: rows.y0,
        z: rows.z0,
      },
    ];

    var data_1 = [
      {
        x: rows.x1,
        y: rows.y1,
        z: rows.z1,
        mode: "markers",
        type: "scatter3d",
        marker: {
          color: "green",
          size: 5,
        },
      },
      {
        alphahull: 7,
        opacity: 0.1,
        type: "mesh3d",
        x: rows.x1,
        y: rows.y1,
        z: rows.z1,
      },
    ];
    var data = data_0.concat(data_1);

    var layout = {
      autosize: true,
      height: window.innerHeight * 0.7,
      scene: {
        aspectratio: {
          x: 1,
          y: 1,
          z: 1,
        },
        camera: {
          center: {
            x: 0,
            y: 0,
            z: 0,
          },
          eye: {
            x: 1.25,
            y: 1.25,
            z: 1.25,
          },
          up: {
            x: 0,
            y: 0,
            z: 1,
          },
        },
        xaxis: {
          type: "linear",
          zeroline: false,
        },
        yaxis: {
          type: "linear",
          zeroline: false,
        },
        zaxis: {
          type: "linear",
          zeroline: false,
        },
      },
      title: "Fradulent emails written by machines vs generated by humans",
      width: window.innerWidth * 0.7,
    };
    Plotly.newPlot("res_viz4", data, layout);
  }
);
